function commit --description 'git scopeal commits'
    if test -n $argv
        set scope $argv[1]
        set description (string join " " $description $argv[2..-1])
        git commit -s -m $scope": "$description
    else
        set whatthecommit (curl -s http://whatthecommit.com/index.txt)
        git commit -s -m "fix: $whatthecommit" -m "Commit generated by whatthecommit.com"
        if type -q lolcat
            echo -e "\n$whatthecommit" | lolcat
        else
            echo -e "\n$whatthecommit"
        end
    end
end
